/**
 * Created by yueziming on 2017-6-8.
 */

var host = location.hostname;
var port = ':2345';
var protocol = location.protocol+'//';

var Api = {
	//url基础配置
	baseUrl:protocol+''+host+''+port+'/api',
	url:{
		//登录接口
		LOGIN:protocol+''+host+''+port+'/oauth/token',
		//左侧菜单接口
		LEFTMENU:protocol+''+host+''+port+'/api/menu-index',
		//主页表格接口
		INDEXTABLE:protocol+''+host+''+port+'/content/ajaxindex/',
		//权限管理页面接口
		RIGHTMANAGEMENT:protocol+''+host+''+port+'/api/permission-index',
		//创建权限字段接口
		PERMISSION:protocol+''+host+''+port+'/api/permission-create',
		//创建权限接口
		CREATERIGHT:protocol+''+host+''+port+'/api/permission-store',
		//编辑权限接口
		EDITRIGHT:protocol+''+host+''+port+'/api/permission-edit-',
		//修改权限接口
		MODIFYRIGHT:protocol+''+host+''+port+'/api/permission-update-',
		//删除权限接口
		DELRIGHT:protocol+''+host+''+port+'/api/permission-delete-',
		//用户管理界面接口
		USERINFO:protocol+''+host+''+port+'/api/user-index',
		//获取添加用户信息接口
		CREATEUSERINFO:protocol+''+host+''+port+'/api/user-create',
		//添加用户接口
		ADDUSER:protocol+''+host+''+port+'/api/user-store',
		//角色列表页面接口
		ROLELIST:protocol+''+host+''+port+'/api/role-index',
		//获取角色接口
		GETROLE:protocol+''+host+''+port+'/api/role-create',
		//创建角色接口
		CREATEROLE:protocol+''+host+''+port+'/api/role-store',
		//删除角色接口
		DELROLE:protocol+''+host+''+port+'/api/role-delete-',
		//获取编辑角色字段接口
		GETEDITROLE:protocol+''+host+''+port+'/api/role-edit-',
		//修改角色接口
		MODIFYROLE:protocol+''+host+''+port+'/api/role-update-',
		//删除用户接口
		DELUSER:protocol+''+host+''+port+'/api/user-delete-',
		//获取修改用户信息接口
		GETMODIFYUSER:protocol+''+host+''+port+'/api/user-edit-',
		//修改用户接口
		MODIFYUSER:protocol+''+host+''+port+'/api/user-update-',
		//添加自定义字段
		ADDFIELD:protocol+''+host+''+port+'/api/column-store',
		//获取所有字段
		GETALLFIELD:protocol+''+host+''+port+'/api/column-index',
		//获取用户关联字段
		GETRELATIONFIELD:protocol+''+host+''+port+'/api/column-list',
		//添加用户关联字段
		ADDRELATIONFIELD:protocol+''+host+''+port+'/api/column-add-',
		//移除用户关联字段
		REMOVERELATIONFIELD:protocol+''+host+''+port+'/api/column-user-delete-',
		//获取用户添加关联字段
		GETSHOWRELATIONFIELD:protocol+''+host+''+port+'/api/column-list',
		//获取用户选择的显示关联字段
		GETSELECTEDRELATIONFIELD:protocol+''+host+''+port+'/api/column-view',
		//设置用户需要显示的字段
		SETSHOWRELATIONFIELD:protocol+''+host+''+port+'/api/column-view-reset',
		//获取内容列表
		GETCONTENTLIST:protocol+''+host+''+port+'/api/access-index',
		//创建内容列表
		CREATECONTENT:protocol+''+host+''+port+'/api/access-create',
		//下载EXCEL内容
		DOWNLOADEXCEL:protocol+''+host+''+port+'/api/access-excel-download',
		//添加内容接口
		ADDCONTENT:protocol+''+host+''+port+'/api/access-store',
		//编辑内容获取信息接口
		GETEDITCONTENT:protocol+''+host+''+port+'/api/access-edit-',
		//修改内容接口
		MODIFYCONTENT:protocol+''+host+''+port+'/api/access-update-',
		//删除内容接口
		DELCONTENT:protocol+''+host+''+port+'/api/access-delete-',
		//导入EXCEL接口
		IMPORTEXCEL:protocol+''+host+''+port+'/api/access-excel-import',
        //获取编辑字段接口
        GEIEDITFIELD:protocol+''+host+''+port+'/api/column-edit-',
        //修改字段接口
        MODIFYFIELD:protocol+''+host+''+port+'/api/column-update-',
        //删除字段接口
        DELFIELD:protocol+''+host+''+port+'/api/column-delete-',
        //公司列表接口
        COMPANNEYLIST:protocol+''+host+''+port+'/api/company-index',
        //添加公司接口
        ADDCOMPANNEY:protocol+''+host+''+port+'/api/company-store',
        //修改公司接口
        MODIFYCOMPANNEY:protocol+''+host+''+port+'/api/company-update-',
        //删除公司接口
        DELCOMPANNEY:protocol+''+host+''+port+'/api/company-delete-',
		//账户信息管理对应公司搜索接口
		COMPANYSEARCH:protocol+''+host+''+port+'/api/company-user',
		//修改密码接口
		MODIFYPASSWORD:protocol+''+host+''+port+'/api/reset-password',
		//获取备份数据列表
		GETBACKUPSDATABASE:protocol+''+host+''+port+'/api/backup-list',
		//添加自动备份
		ADDBACKUPSDATABASE:protocol+''+host+''+port+'/api/backup-export',
		//还原备份接口
        REDUCEBACKUPSDATABASE:protocol+''+host+''+port+'/api/backup-reduction',
		//删除备份接口
        DELBACKUPSDATABASE:protocol+''+host+''+port+'/api/backup-delete'
	},
	localJson:{
		//左侧菜单接口
		LEFTMENU:'json/menu.json',
		//主页表格接口
		INDEXTABLE:'json/test.json',
		//获取
        GETCONTENTLIST:'json/access-index.json'
	}
};